config/routes.rb
Recipes::Application.routes.draw do

  resources :users do
    resources :recipes do
      resources :steps
      resources :ingredients
    end
  end

  resources :recipes, only: [:index, :show]  do # Show all recipes
    get 'tags', on: :collection
  end
  resource :search

  get 'app' => 'templates#app'  # <- Starting point of our AngularJS app.
  get 'templates/index.html' => 'templates#index'
  get 'templates/recipe.html' => 'templates#recipe'
  get 'templates/pagination.html' => 'templates#pagination'

  root 'templates#app'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe

  validates_presence_of :description
end

# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  recipe_id   :integer
#  amount      :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  unit        :string(255)
#

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :ingredients, -> { order "id" }  # FIXME: add position
  has_many :steps, -> { order "position" }

  accepts_nested_attributes_for :ingredients, :steps, allow_destroy: true
  acts_as_taggable

  validates_presence_of :title
end

# == Schema Information
#
# Table name: recipes
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  image_url   :string(255)
#

app/models/recipe_downloader.rb
# Downloading from http://dsquirrel.tripod.com/recipeml/indexrecipes2.html
require 'open-uri'
require 'zip'

class RecipeDownloader
  BASE_URL = "http://dsquirrel.tripod.com/xmlzips/RecipeMLArchive{1}.zip"

  def parse_all(user)
    @user = user
    110.times do |i|
      filenumber = (i+1).to_s.rjust(5, '0')
      url = BASE_URL.sub("{1}", filenumber)
      parse_file url
    end
  end

  def parse_file(zipfilename)
    puts "Loading #{zipfilename}"
    Zip::InputStream.open(open(zipfilename)) do |zis|
      while entry = zis.get_next_entry do
        parse_zip_entry(entry, zis.read)
      end
    end
  end

  def parse_zip_entry(entry, content)
      name = entry.name[4..-5] # i.e "xml/#10_Cake.xml"
      puts "Name: #{name}"
      xml = Hash.from_xml(content)

      # recipe
      recipe = xml["recipeml"]["recipe"]
      title = recipe["head"]["title"]
      image_url = get_image_url(title||name)
      categories = Array.wrap(recipe["head"]["categories"]["cat"]).join(', ')
      steps = recipe["directions"]["step"]
      ingredients = recipe["ingredients"]

      new_recipe = @user.recipes.create(title: title.to_s[0..254],
                                        description: nil,
                                        image_url: image_url&&image_url.length<255 ? image_url : nil,
                                        tag_list: categories&&categories.length<255 ? categories : nil)

      # steps
      if steps.nil?
        puts "\tno steps"
      elsif steps.is_a?(String)
        puts "\tSteps:#{}"
        new_recipe.steps.create(position:1,   description: steps.to_s[0..254] )
      else
        #Anything else out there?
        puts "\tSteps:#{steps.class} !!!!!"
      end

      # intgredients
      if ingredients.nil?
        puts "\tno ingredients"
      elsif ingredients["ing_div"].is_a?(Hash)
        puts "\tSingle"
        ingredient_group = ingredients['ing_div']
        title = ingredient_group['title']
        ingredient_entries = ingredient_group['ing']
        add_ingredients(new_recipe, ingredient_entries, title)
      elsif ingredients["ing_div"].is_a?(Array)
        puts "\tComplex"
        ingredients["ing_div"].each do |ingredient_group|
          title = ingredient_group['title']
          ingredient_entries = ingredient_group['ing'] # array of {"amt"=>{"qty"=>"50", "unit"=>nil}, "item"=>"MILK SKIM FILLED 1/2 PT"}
          add_ingredients(new_recipe, ingredient_entries, title)
        end
      else
        ingredient_entries = ingredients["ing"]
        add_ingredients(new_recipe, ingredient_entries)
      end
  end

  def add_ingredients(recipe, ingredients, title=nil)
    return unless ingredients
    puts "\tIngredients #{title}=>#{ingredients.length}"
    recipe.ingredients.create(amount: nil, description: title ) if title  # FIXME: Adding a title in between ingredients...maybe we should adapt the model (recipe has one or more parts that each have many ingredients?)
    Array.wrap(ingredients).each do |ingredient|
      recipe.ingredients.create(amount: ingredient["amt"]["qty"], unit: ingredient["amt"]["unit"], description: ingredient["item"] )
    end
  end

  def get_image_url(name)
    name = name.gsub(/[^A-Za-z0-9]/, " ")
    images = Google::Search::Image.new(:query => name, imgsz: "small")
    images.first.uri if images.first rescue nil
  end
end

app/models/recipe_search.rb
# Read-only model based on a view generated in postgres that includes
# the recipe information and the ingredients flattened out into a string
class RecipeSearch < ActiveRecord::Base
  belongs_to :recipe

  def readonly?
    true
  end

  def self.search(query,page=1)
    RecipeSearch.basic_search(query).page(page)
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :recipe
end

# == Schema Information
#
# Table name: steps
#
#  id          :integer          not null, primary key
#  recipe_id   :integer
#  position    :integer
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
end

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  twitter    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_action :no_cache

  # FROM: http://stackoverflow.com/questions/19883497/heroku-rails-cors-issue
  # def cors_preflight_check
  #   headers['Access-Control-Max-Age'] = '1728000'
  #
  #   render json: {} # Render as you need
  # end

  protected

  def no_cache
    # response.headers['Last-Modified'] = Time.now.httpdate
    expires_now
  end

end

app/controllers/recipes_controller.rb
class RecipesController < InheritedResources::Base
  respond_to :html, :json
  belongs_to :user, :optional => true

  def tags
    respond_with(Recipe.tag_counts)
  end

  protected

  def permitted_params
    params.permit(recipe: [:title, :description, :image_url,
                              :tag_list => [],
                              :ingredients_attributes => ["id", "amount", "unit", "description", "recipe_id", "_destroy"],
                              :steps_attributes => ["id", "position", "description", "recipe_id", "_destroy"]])
  end

  def collection
    if params[:tag].present?
      @recipes ||= end_of_association_chain.tagged_with(params[:tag]).page(params[:page])
    elsif params[:search]
      @results = RecipeSearch.search(params[:search],params[:page])
      @results.each_with_index {|rs, i| @results[i] = rs.recipe }  # was .map(&:recipe), but we want to keep pagination intact
      @recipes = @results
    else
      @recipes ||= end_of_association_chain.page(params[:page])
    end
    @recipes
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @query = params[:query]
    @results = RecipeSearch.search(@query,params[:page])
    @recipes = @results.map(&:recipe)
    render json: @recipes, meta: { current_page: @results.current_page, 
                                   num_pages: @results.num_pages,
                                   limit_value: @results.limit_value }
  end
end

app/controllers/templates_controller.rb
# Just to serve AngularJS template files. Could also simply serve plain assets
class TemplatesController < ApplicationController
  layout false

  def app
    render 'app', layout:'application'
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  protected
  def permitted_params
    params.permit(user: [:twitter])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Recipes
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{name:"viewport", content:"width=device-width, initial-scale=1.0"}

    %link{rel: "stylesheet", href:"//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"}
    %link{rel: "stylesheet", href:"//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css"}
    %script{src: "//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"}
  %body

app/views/templates/app.html.haml
%div
  %div{ "ng-view" => "main" }

app/views/templates/index.html.haml
.btn-group
  %button.btn.btn-default{type: "button", "ng-click" => "showList()", "ng-class" => "{'btn-primary': viewStyle == 'list'} "}
    %span.glyphicon.glyphicon-th-list
  %button.btn.btn-default{type: "button", "ng-click" => "showThumbnails()", "ng-class" => "{'btn-primary': viewStyle == 'thumbnails'} "}
    %span.glyphicon.glyphicon-th-large
  %button.btn.btn-default{type: "button", "ng-click" => "showCloud()", "ng-class" => "{'btn-primary': viewStyle == 'cloud'} "}
    %span.glyphicon.glyphicon-cloud


%div{ "ng-switch" => true,  "on" => "viewStyle" }

  #listView{"ng-switch-when" => "list"}
    %div{ 'ng-include' => "'templates/pagination.html'" }
    %table.table.table-striped.table-bordered
      %tr
        %th
        %th Title
        %th
      %tr{ 'ng-repeat' => "recipe in recipes" }
        %td
          %img{ 'ng-src' => "{{recipe.imageUrl}}", class: 'img-thumbnail', style: 'width:64px' }
        %td {{ recipe.title }}
        %td
          %a{ 'ng-click' => "showRecipe(recipe)"} Show

  #thumbnailsView{"ng-switch-when" => "thumbnails"}
    %div{ 'ng-include' => "'templates/pagination.html'" }
    .row
      .col-sm-6.col-md-4{ 'ng-repeat' => "recipe in recipes", 'ng-click' => "showRecipe(recipe)" }
        .thumbnail
          %img{ 'ng-src' => "{{recipe.imageUrl}}", style: 'width:180px; height:200px' }
          .caption
            {{ recipe.title }}

  #thumbnailsView{"ng-switch-when" => "cloud"}
    %nav
      %a{ 'ng-repeat' => "tag in tags", 'ng-click' => "selectTag(tag)", "class" => "{{tag.css}}", 'ng-if' => "tag.index>1" } {{tag.name}}

app/views/templates/pagination.html.haml
Page {{pagination.currentPage}}/{{pagination.totalPages}}
%a{ 'ng-click' => 'previousPage()', 'ng-if' => "pagination.hasPrevious"}
  <<
%a{ 'ng-click' => 'nextPage()', 'ng-if' => "pagination.hasNext"}
  >>

app/views/templates/recipe.html.haml
:css
  .textbox {
      height: 150px;
      width: 100%;
  }
  .strike {
    opacity:0.4;
    text-decoration: line-through;
  }

%form#recipeForm{ name: "recipeForm", "novalidate" => "true" }
  %p
    %b{ 'ng-hide' => 'editing' }
      Title: {{selectedRecipe.title}}
    .field{ 'ng-show' => 'editing', "ng-class" => "{'has-error': recipeForm.title.$invalid}"}
      %label Title
      %input#title.form-control{ "name" => "title", "ng-model" => "selectedRecipe.title", type: "text", "required" => false, "ng-minlength" => 5, "server-error" => true}
      %span.help-block{"ng-show" => "recipeForm.title.$dirty && recipeForm.title.$error.required"} Required
      %span.help-block{"ng-show" => "recipeForm.title.$dirty && recipeForm.title.$error.minlength"} At least 5 characters
      %span.help-block{"ng-show" => "recipeForm.title.$error.server"}
        {{ errors.title }}
  %p{ 'ng-hide' => 'editing' }
    %b
      Description: {{selectedRecipe.description}}
    .field{ 'ng-show' => 'editing' }
      %label Description
      %textarea#recipe_description.form-control{ "ng-model" => "selectedRecipe.description" }
  %p
    %span{ 'ng-hide' => 'editing' } {{selectedRecipe.tagList.join(", ")}}
    %tags-input{ "ng-model" => "selectedRecipe.tagList", 'ng-show' => 'editing' }

  %a.btn.btn-primary{ 'ng-hide' => "editing",  'ng-click' => "edit()" } Edit

  %tabset

    %tab{heading: "Ingredients ({{selectedRecipe.ingredients.length}})"}

      %table.table.table-striped.table-bordered
        %tr
          %th Amount
          %th Description
          %th

        %tr{ 'ng-repeat' => "ingredient in selectedRecipe.ingredients", 'ng-class' => "{strike: ingredient._destroy}" }
          %td
            %span{ 'ng-hide' => 'editing' } {{ingredient.amount}} {{ingredient.unit}}
            %input{ 'ng-show' => 'editing', 'type' => "text", 'ng-model' => "ingredient.amount", 'placeholder' => "Amount" }
            %input{ 'ng-show' => 'editing', 'type' => "text", 'ng-model' => "ingredient.unit", 'placeholder' => "Unit" }
          %td
            %ng-form{ name: "ingredientForm" }
              %span{ 'ng-hide' => 'editing' } {{ingredient.description}}
              .field{ 'ng-show' => 'editing', "ng-class" => "{'has-error': ingredientForm.description.$invalid}"}
                %input{ 'name' => 'description', 'ng-show' => 'editing', 'type' => "text", 'ng-model' => "ingredient.description", 'placeholder' => "Description", 'required' => true, "ng-minlength" => 3}
                %span.help-block{"ng-show" => "ingredientForm.description.$dirty && ingredientForm.description.$error.required"} Required
                %span.help-block{"ng-show" => "ingredientForm.description.$dirty && ingredientForm.description.$error.minlength"} At least 3 characters

          %td
            %a{ 'ng-click' => "deleteIngredient(ingredient)", 'ng-show' => 'editing'} Destroy

      %a{'ng-show' => 'editing', 'ng-click' => "addIngredient()" } New Ingredient

    %tab{heading: "Steps ({{selectedRecipe.steps.length}})"}

      %table.table.table-striped.table-bordered
        %tr
          %th Position
          %th Description
          %th

        %tr{ 'ng-repeat' => "step in selectedRecipe.steps", 'ng-class' => "{strike: step._destroy}" }
          %td
            %span{ 'ng-hide' => 'editing&&!step._destroy' } {{step.position}}
            %input{ 'ng-show' => 'editing&&!step._destroy', 'type' => "text", 'ng-model' => "step.position", 'placeholder' => "Position", 'required' => true }
          %td
            %span{ 'ng-hide' => 'editing&&!step._destroy' } {{step.description}}
            %textarea.textbox{ 'ng-show' => 'editing&&!step._destroy', 'type' => "text", 'ng-model' => "step.description", 'placeholder' => "Description", 'required' => true }
          %td
            %a{ 'ng-click' => "deleteStep(step)", 'ng-show' => 'editing'} Destroy

      %a{ 'ng-show' => 'editing', 'ng-click' => "addStep()"  } New Step

  %span{ 'ng-show' => 'editing' }
    %a.btn.btn-primary{ 'ng-click' => "save()", "ng-disabled" => "!recipeForm.$valid" } Save
    or
    %a{ 'ng-click' => "cancel()" } Cancel

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :twitter
    = f.text_field :twitter, class: "form-control"
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table.table.table-striped.table-bordered
  %tr
    %th Twitter
    %th
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.twitter
      %td= link_to 'Recipies', user_recipes_path(user)
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Twitter:
  = @user.twitter

= link_to 'Recipies', user_recipes_path(@user)
\|
= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path